### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by setarekhosravi** [TsingWei/LiteTrack#7]
Hi, Thank you for your great work.
when I run video_demo.py or the below script I face an error:
`python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output
Traceback (most recent call last):
  File "/media/strh/MyDrive/Track/OtherTracking/LiteTrack/tracking/create_default_local_file.py", line 5, in <module>
    from lib.test.evaluation import create_default_local_file_ITP_test
  File "/media/strh/MyDrive/Track/OtherTracking/LiteTrack/tracking/../lib/test/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "/media/strh/MyDrive/Track/OtherTracking/LiteTrack/tracking/../lib/test/evaluation/data.py", line 3, in <module>
    from lib.train.data.image_loader import imread_indexed
ModuleNotFoundError: No module named 'lib.train.data'
`
At this stage I just want to run the demo, I don't want to train or test your model.
Please help me to solve it.

Another question is where is your installation script?

**Comment by TsingWei** [comment]
Sry for the mising of some files.  The mising of `lib.train.data' is caused by the uncorrect config in the `.gitignore` where I put `data` in it, for ignoring the datasets folder (I thought it would match the absolute path in the gitignore file).  
A quick fix is, just copy the folder and installation script from OSTrack like [here] (https://github.com/TsingWei/LiteTrack/issues/3#issuecomment-2017375539) does.
